/*
 * The MIT License
 *
 * Copyright 2014 Drew.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package tzk.image.ui;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author Drew
 */
public class Easel extends javax.swing.JPanel {

    /**
     * Creates new form Easel
     */
    public Easel() {
        initComponents();
    }

    public Easel(ImageCraft iC) {
        imageCraft = iC;
        initComponents();
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public static void main(String args) {

    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 585, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 345, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        //Horizontal
        
        System.out.println(evt.getX() + " " + evt.getY());
        if (evt.getX() > width - 10
                && evt.getY() < (height - 10) / 2
                && evt.getY() > (height - 10) / 2 + 10) {
            //right/horizontal
            System.out.println("horizon");
        } else if (evt.getY() > height - 10
                && evt.getX() > (width - 10) / 2
                && evt.getX() < (width - 10) / 2 + 10) {
            //bottom/vertical
            System.out.println("vertica");

//        } else if (evt.getY() > height - 10
//                && evt.getX() > width - 10) {
//            //corner
//            System.out.println("corner");

        }


    }//GEN-LAST:event_formMouseDragged

    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
       
     
        width = this.getWidth();
        height = this.getHeight();
        
        g.setColor(Color.BLUE);
        g.fillRect(width - 10, (height - 10) / 2, 10, 10);//horizontal resizer
        g.fillRect(width - 10, height - 10, 10, 10);//corner rezier
        g.fillRect((width - 10) / 2, height - 10, 10, 10);
 
        revalidate();
        repaint();
    }

    public ImageCraft imageCraft;
    public int height, width;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
